name: Python application

on:
  push:
  #schedule:
  #  - cron: '0 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Script
      env:
        GSHEETS_CREDS_JSON: ${{ secrets.GSHEETS_CREDS_JSON }}
        GSHEET_KEY: ${{ secrets.GSHEET_KEY }}
        CSV_LINK: ${{secrets.CSV_LINK}} 
      run: python csv_to_gsheets.py
